# Generated by Django 4.1.3 on 2022-12-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Therapy', models.CharField(max_length=100, verbose_name='Therapy')),
            ],
            options={
                'verbose_name': 'Therapy',
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Online', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Online Price')),
                ('In_Person', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='In Person Price')),
                ('Therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimBurns.therapies', verbose_name='Therapy')),
            ],
            options={
                'verbose_name': 'Price',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25, verbose_name='Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Type', models.CharField(choices=[('Online', 'Online'), ('In Person', 'In Person')], max_length=100, verbose_name='Type')),
                ('Message', models.CharField(max_length=1000, verbose_name='Message')),
                ('Date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('Therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimBurns.therapies', verbose_name='Therapy')),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
