# Generated by Django 4.1.3 on 2022-11-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TimBurns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25, verbose_name='Name')),
                ('Email', models.EmailField(max_length=254, verbose_name='Email')),
                ('Phone', models.IntegerField(verbose_name='Phone')),
                ('Therapy', models.CharField(choices=[('EMDR', 'EMDR'), ('Couple', 'Couple')], max_length=100, verbose_name='Therapy')),
                ('Type', models.CharField(choices=[('Online', 'Online'), ('In Person', 'In Person')], max_length=100, verbose_name='Type')),
                ('Message', models.CharField(max_length=1000, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Message',
            },
        ),
    ]
