# Generated by Django 4.1.3 on 2022-11-18 15:59

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('TimBurns', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31),
        ),
    ]
