# Generated by Django 4.1.3 on 2022-11-18 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TimBurns', '0003_alter_message_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
