# Generated by Django 4.1.3 on 2022-11-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimBurns', '0004_message_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='Phone',
        ),
    ]
