# Generated by Django 4.1.3 on 2022-11-19 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimBurns', '0005_remove_message_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Therapy', models.CharField(max_length=100, verbose_name='Therapy')),
            ],
            options={
                'verbose_name': 'Therapies',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='Therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimBurns.therapies', verbose_name='Therapies'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='Therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimBurns.therapies', verbose_name='Therapies'),
        ),
    ]
