# Generated by Django 4.1.3 on 2022-11-25 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TimBurns', '0006_therapies_alter_message_therapy_alter_prices_therapy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='therapies',
            options={'verbose_name': 'Therapy'},
        ),
        migrations.RemoveField(
            model_name='prices',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='Type',
        ),
        migrations.AddField(
            model_name='prices',
            name='In_Person',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4, verbose_name='In Person Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prices',
            name='Online',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4, verbose_name='Online Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='Therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimBurns.therapies', verbose_name='Therapy'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='Therapy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TimBurns.therapies', verbose_name='Therapy'),
        ),
    ]
