# Generated by Django 4.1.3 on 2022-12-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimBurns', '0007_alter_prices_options_alter_therapies_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'Price'},
        ),
    ]
